export const FETCH_USER = 'FETCH_USER';

export const FETCH_TODAY_MENU_REQUEST = 'FETCH_TODAY_MENU_REQUEST';
export const FETCH_TODAY_MENU_FAILURE = 'FETCH_TODAY_MENU_FAILURE';
export const FETCH_TODAY_MENU_SUCCESS = 'FETCH_TODAY_MENU_SUCCESS';

export const ADD_ORDER_ITEM_TO_CART = 'ADD_ORDER_ITEM_TO_CART';
export const REMOVE_ORDER_ITEM_FROM_CART = 'REMOVE_ORDER_ITEM_FROM_CART';
export const INCREMENT_ORDER_ITEM_COUNT = 'INCREMENT_ORDER_ITEM_COUNT';
export const DECREMENT_ORDER_ITEM_COUNT = 'DECREMENT_ORDER_ITEM_COUNT';
