export const FETCH_USER = 'FETCH_USER';

export const FETCH_TODAY_MENU_REQUEST = 'FETCH_TODAY_MENU_REQUEST';
export const FETCH_TODAY_MENU_FAILURE = 'FETCH_TODAY_MENU_FAILURE';
export const FETCH_TODAY_MENU_SUCCESS = 'FETCH_TODAY_MENU_SUCCESS';
