export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_TODAY_MENU_REQUEST = 'FETCH_TODAY_MENU_REQUEST';
export const FETCH_TODAY_MENU_FAILURE = 'FETCH_TODAY_MENU_FAILURE';
export const FETCH_TODAY_MENU_SUCCESS = 'FETCH_TODAY_MENU_SUCCESS';

export const ADD_ORDER_ITEM_TO_CART = 'ADD_ORDER_ITEM_TO_CART';
export const REMOVE_ORDER_ITEM_FROM_CART = 'REMOVE_ORDER_ITEM_FROM_CART';
export const INCREMENT_ORDER_ITEM_COUNT = 'INCREMENT_ORDER_ITEM_COUNT';
export const DECREMENT_ORDER_ITEM_COUNT = 'DECREMENT_ORDER_ITEM_COUNT';

export const SUBMIT_ORDER_REQUEST = 'SUBMIT_ORDER_REQUEST';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';
export const SUBMIT_ORDER_FAILURE = 'SUBMIT_ORDER_FAILURE';

export const ORDER_CONFIRMATION = 'ORDER_CONFIRMATION';

export const CLEAR_CART = 'CLEAR_CART';

export const SUBMIT_LOGIN_REQUEST = 'SUBMIT_LOGIN_REQUEST';
export const SUBMIT_LOGIN_FAILURE = 'SUBMIT_LOGIN_FAILURE';
export const SUBMIT_LOGIN_SUCCESS = 'SUBMIT_LOGIN_SUCCESS';

export const SUBMIT_REGISTER_REQUEST = 'SUBMIT_REGISTER_REQUEST';
export const SUBMIT_REGISTER_FAILURE = 'SUBMIT_REGISTER_FAILURE';
export const SUBMIT_REGISTER_SUCCESS = 'SUBMIT_REGISTER_SUCCESS';
